binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
chain_width = 60
color = "Always"
combine_control_expr = true
comment_width = 100 # Fuchsia uses 100
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
empty_item_single_line = true
enum_discrim_align_threshold = 20
error_on_line_overflow = false
error_on_unformatted = false
fn_params_layout = "Tall"
fn_call_width = 60
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
format_strings = true # otherwise strings will violate max_width
group_imports = "StdExternalCrate"
hard_tabs = false
hide_parse_errors = false
imports_indent = "Visual"
imports_layout = "HorizontalVertical"
indent_style = "Block"
match_arm_blocks = true
match_block_trailing_comma = true
max_width = 100
merge_derives = true
merge_imports = false
newline_style = "Unix"
normalize_comments = false
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
remove_blank_lines_at_start_or_end_of_block = true
reorder_impl_items = false
report_fixme = "Never"
report_todo = "Never"
short_array_element_width_threshold = 10
skip_children = false
single_line_if_else_max_width = 50
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
spaces_within_parens_and_brackets = false
struct_field_align_threshold = 20
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = false
use_field_init_shorthand = false
use_small_heuristics = "Default"
use_try_shorthand = true # Fuchsia prefers the shortcut
where_single_line = false
wrap_comments = true # otherwise comments will violate max_width